### ISSUE TITLE
No such method error `asw.l()Lij`

### ISSUE THREAD

**Issue by norganna** [notjoe7F/stockpile#1]
Getting the following error with Minecraft 0.13, Rift 1.0.3-41 and stockpile 0.1.0 (no other mods installed):

```
[10:31:58] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: asw.l()Lij;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
	at k.a(SourceFile:199) [k.class:?]
	at net.minecraft.server.MinecraftServer.w(SourceFile:701) [MinecraftServer.class:?]
	at sn.w(SourceFile:357) [sn.class:?]
	at net.minecraft.server.MinecraftServer.v(SourceFile:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:559) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoSuchMethodError: asw.l()Lij;
	at notjoe.stockpile.tile.TileBarrel.displayBarrelContents(TileBarrel.kt:109) ~[TileBarrel.class:?]
	at notjoe.stockpile.tile.TileBarrel.handleRightClick(TileBarrel.kt:83) ~[TileBarrel.class:?]
	at notjoe.stockpile.block.BlockBarrel.a(BlockBarrel.kt:79) ~[BlockBarrel.class:?]
	at bkt.a(SourceFile:281) ~[bkt.class:?]
	at tf.a(SourceFile:313) ~[tf.class:?]
	at ub.a(SourceFile:918) ~[ub.class:?]
	at nr.a(SourceFile:53) ~[nr.class:?]
	at nr.a(SourceFile:11) ~[nr.class:?]
	at ix.a(SourceFile:10) ~[ix.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
	at k.a(SourceFile:198) ~[k.class:?]
	... 5 more
```

This error occurs when I try to interact (left or right click) with the item.

I also cannot break the item successfully.

**Comment by norganna** [comment]
Never mind, I just worked out you have to break the item from the non-face side.

**Comment by notjoe7F** [comment]
The latest version of Stockpile was tested on Rift 1.0.2-33 (the latest CurseForge version), so there might be some changes in the mappings that warrant recompiling the mod. I'm not aware of any breaking changes between those versions, but I'll investigate further when I get the chance.

**Comment by notjoe7F** [comment]
Just pushed a new version built against Rift 1.0.3-45 -- this appears to fix the issue, closing for now.

**Comment by norganna** [comment]
Yes, this works for me.
