### ISSUE TITLE
Crashes on 1.13.2

### ISSUE THREAD

**Issue by Seegras** [notjoe7F/stockpile#13]
Using Rift for 1.13.2 https://minecraft.curseforge.com/linkout?remoteUrl=https://jitpack.io/com/github/chocohead/rift/2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff/rift-2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff.jar

it crashes (Riftlin 0.0.3 alone does not crash, only with Stockpile):

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: notjoe/stockpile/block/BlockBarrel
	at notjoe.stockpile.block.StockpileBlocks.<clinit>(StockpileBlocks.kt:15) ~[StockpileBlocks.class:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcs.handler$onRegisterBlocks$zzc000(SourceFile:1820) ~[bcs.class:?]
	at bcs.t(SourceFile:1738) ~[bcs.class:?]
	at pf.c(SourceFile:464) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: notjoe.stockpile.block.BlockBarrel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at notjoe.stockpile.block.StockpileBlocks.<clinit>(StockpileBlocks.kt:15) ~[StockpileBlocks.class:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcs.handler$onRegisterBlocks$zzc000(SourceFile:1820) ~[bcs.class:?]
	at bcs.t(SourceFile:1738) ~[bcs.class:?]
	at pf.c(SourceFile:464) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_191]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_191]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at notjoe.stockpile.block.StockpileBlocks.<clinit>(StockpileBlocks.kt:15) ~[StockpileBlocks.class:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:248) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
	at bcs.handler$onRegisterBlocks$zzc000(SourceFile:1820) ~[bcs.class:?]
	at bcs.t(SourceFile:1738) ~[bcs.class:?]
	at pf.c(SourceFile:464) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 6 more

**Comment by notjoe7F** [comment]
Apologies for the late response. It looks like Stockpile needs to be updated for the new version, as it hasn't been updated since before Rift was available for 1.13.2. I'll try to get this done at some point within the next few days.

**Comment by notjoe7F** [comment]
The Rift version of Stockpile has been retired in favor of 0.4 and later on Fabric. As such, this issue will be closed-- but, if the issue persists on 0.4 or later, please post about it!
